version: "3.9"

services:
  web:
    build:
      context: "frontend"
    container_name: "travelers-web"
    ports:
      - "8080:80"
  api:
    build:
      context: "WebApi"
    container_name: "travelers-api"
    ports:
      - "8081:80"
    depends_on:
      - "db"
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "travelers-db-container"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongP@ssword
    ports:
      - "8092:1433"
    volumes:
      - travelers:/var/opt/mssql:rw
