version: "3.9"

services:
  web:
    build:
      context: "frontend"
    container_name: "travelers-web"
    ports:
      - "8080:80"
  api:
    build:
      context: "WebApi"
    container_name: "travelers-api"
    ports:
      - "8081:80"
