version: "3.9"

services:
  web:
    build:
      context: "frontend"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"
  api:
    build:
      context: "WebApi"
    container_name: "travelers-api"
    ports:
      - "${API_PORT}:80"
    depends_on:
      - "db"
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "${DB_CONT_NAME}"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongP@ssword
    ports:
      - "8092:1433"
    volumes:
      - travelers:/var/opt/mssql:rw
